/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Files Not Found
 */
export type GetFilesResponseBodyData = {
  message: string;
};

/**
 * Files Not Found
 */
export class GetFilesResponseBody extends Error {
  /** The original data that was passed to this error instance. */
  data$: GetFilesResponseBodyData;

  constructor(err: GetFilesResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.name = "GetFilesResponseBody";
  }
}

/** @internal */
export const GetFilesResponseBody$inboundSchema: z.ZodType<
  GetFilesResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
})
  .transform((v) => {
    return new GetFilesResponseBody(v);
  });

/** @internal */
export type GetFilesResponseBody$Outbound = {
  message: string;
};

/** @internal */
export const GetFilesResponseBody$outboundSchema: z.ZodType<
  GetFilesResponseBody$Outbound,
  z.ZodTypeDef,
  GetFilesResponseBody
> = z.instanceof(GetFilesResponseBody)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetFilesResponseBody$ {
  /** @deprecated use `GetFilesResponseBody$inboundSchema` instead. */
  export const inboundSchema = GetFilesResponseBody$inboundSchema;
  /** @deprecated use `GetFilesResponseBody$outboundSchema` instead. */
  export const outboundSchema = GetFilesResponseBody$outboundSchema;
  /** @deprecated use `GetFilesResponseBody$Outbound` instead. */
  export type Outbound = GetFilesResponseBody$Outbound;
}
