/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Products Not Found
 */
export type GetProductsResponseBodyData = {
  message: string;
};

/**
 * Products Not Found
 */
export class GetProductsResponseBody extends Error {
  /** The original data that was passed to this error instance. */
  data$: GetProductsResponseBodyData;

  constructor(err: GetProductsResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.name = "GetProductsResponseBody";
  }
}

/** @internal */
export const GetProductsResponseBody$inboundSchema: z.ZodType<
  GetProductsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
})
  .transform((v) => {
    return new GetProductsResponseBody(v);
  });

/** @internal */
export type GetProductsResponseBody$Outbound = {
  message: string;
};

/** @internal */
export const GetProductsResponseBody$outboundSchema: z.ZodType<
  GetProductsResponseBody$Outbound,
  z.ZodTypeDef,
  GetProductsResponseBody
> = z.instanceof(GetProductsResponseBody)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetProductsResponseBody$ {
  /** @deprecated use `GetProductsResponseBody$inboundSchema` instead. */
  export const inboundSchema = GetProductsResponseBody$inboundSchema;
  /** @deprecated use `GetProductsResponseBody$outboundSchema` instead. */
  export const outboundSchema = GetProductsResponseBody$outboundSchema;
  /** @deprecated use `GetProductsResponseBody$Outbound` instead. */
  export type Outbound = GetProductsResponseBody$Outbound;
}
