/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Payment Links Not Found
 */
export type GetPaymentLinksResponseBodyData = {
  message: string;
};

/**
 * Payment Links Not Found
 */
export class GetPaymentLinksResponseBody extends Error {
  /** The original data that was passed to this error instance. */
  data$: GetPaymentLinksResponseBodyData;

  constructor(err: GetPaymentLinksResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.name = "GetPaymentLinksResponseBody";
  }
}

/** @internal */
export const GetPaymentLinksResponseBody$inboundSchema: z.ZodType<
  GetPaymentLinksResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
})
  .transform((v) => {
    return new GetPaymentLinksResponseBody(v);
  });

/** @internal */
export type GetPaymentLinksResponseBody$Outbound = {
  message: string;
};

/** @internal */
export const GetPaymentLinksResponseBody$outboundSchema: z.ZodType<
  GetPaymentLinksResponseBody$Outbound,
  z.ZodTypeDef,
  GetPaymentLinksResponseBody
> = z.instanceof(GetPaymentLinksResponseBody)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetPaymentLinksResponseBody$ {
  /** @deprecated use `GetPaymentLinksResponseBody$inboundSchema` instead. */
  export const inboundSchema = GetPaymentLinksResponseBody$inboundSchema;
  /** @deprecated use `GetPaymentLinksResponseBody$outboundSchema` instead. */
  export const outboundSchema = GetPaymentLinksResponseBody$outboundSchema;
  /** @deprecated use `GetPaymentLinksResponseBody$Outbound` instead. */
  export type Outbound = GetPaymentLinksResponseBody$Outbound;
}
