/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Prices Not Found
 */
export type GetPricesResponseBodyData = {
  message: string;
};

/**
 * Prices Not Found
 */
export class GetPricesResponseBody extends Error {
  /** The original data that was passed to this error instance. */
  data$: GetPricesResponseBodyData;

  constructor(err: GetPricesResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.name = "GetPricesResponseBody";
  }
}

/** @internal */
export const GetPricesResponseBody$inboundSchema: z.ZodType<
  GetPricesResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
})
  .transform((v) => {
    return new GetPricesResponseBody(v);
  });

/** @internal */
export type GetPricesResponseBody$Outbound = {
  message: string;
};

/** @internal */
export const GetPricesResponseBody$outboundSchema: z.ZodType<
  GetPricesResponseBody$Outbound,
  z.ZodTypeDef,
  GetPricesResponseBody
> = z.instanceof(GetPricesResponseBody)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetPricesResponseBody$ {
  /** @deprecated use `GetPricesResponseBody$inboundSchema` instead. */
  export const inboundSchema = GetPricesResponseBody$inboundSchema;
  /** @deprecated use `GetPricesResponseBody$outboundSchema` instead. */
  export const outboundSchema = GetPricesResponseBody$outboundSchema;
  /** @deprecated use `GetPricesResponseBody$Outbound` instead. */
  export type Outbound = GetPricesResponseBody$Outbound;
}
