/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customersCreate } from "../funcs/customersCreate.js";
import { customersList } from "../funcs/customersList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Customers extends ClientSDK {
  /**
   * List of all customers
   *
   * @remarks
   * List of all customers
   */
  async list(
    options?: RequestOptions,
  ): Promise<Array<operations.GetCustomersResponseBody>> {
    return unwrapAsync(customersList(
      this,
      options,
    ));
  }

  /**
   * Create a customer
   *
   * @remarks
   * Create a customer
   */
  async create(
    request: operations.PostCustomersRequestBody,
    options?: RequestOptions,
  ): Promise<operations.PostCustomersResponseBody> {
    return unwrapAsync(customersCreate(
      this,
      request,
      options,
    ));
  }
}
