/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { filesCreate } from "../funcs/filesCreate.js";
import { filesList } from "../funcs/filesList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Files extends ClientSDK {
  /**
   * List all files
   *
   * @remarks
   * List all files
   */
  async list(
    options?: RequestOptions,
  ): Promise<Array<operations.GetFilesResponseBody>> {
    return unwrapAsync(filesList(
      this,
      options,
    ));
  }

  /**
   * Create a file
   *
   * @remarks
   * Create a file
   */
  async create(
    request: operations.PostFilesRequestBody,
    options?: RequestOptions,
  ): Promise<operations.PostFilesResponseBody> {
    return unwrapAsync(filesCreate(
      this,
      request,
      options,
    ));
  }
}
