/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { pricesCreate } from "../funcs/pricesCreate.js";
import { pricesList } from "../funcs/pricesList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Prices extends ClientSDK {
  /**
   * List of all prices
   *
   * @remarks
   * List of all prices
   */
  async list(
    options?: RequestOptions,
  ): Promise<Array<operations.GetPricesResponseBody>> {
    return unwrapAsync(pricesList(
      this,
      options,
    ));
  }

  /**
   * Create a price
   *
   * @remarks
   * Create a price
   */
  async create(
    request: operations.PostPricesRequestBody,
    options?: RequestOptions,
  ): Promise<operations.PostPricesResponseBody> {
    return unwrapAsync(pricesCreate(
      this,
      request,
      options,
    ));
  }
}
