/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { productsCreate } from "../funcs/productsCreate.js";
import { productsList } from "../funcs/productsList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Products extends ClientSDK {
  /**
   * List of all products
   *
   * @remarks
   * List of all products
   */
  async list(
    options?: RequestOptions,
  ): Promise<Array<operations.GetProductsResponseBody>> {
    return unwrapAsync(productsList(
      this,
      options,
    ));
  }

  /**
   * Create a product
   *
   * @remarks
   * Create a product
   */
  async create(
    request: operations.PostProductsRequestBody,
    options?: RequestOptions,
  ): Promise<operations.PostProductsResponseBody> {
    return unwrapAsync(productsCreate(
      this,
      request,
      options,
    ));
  }
}
