/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Businesses } from "./businesses.js";
import { Customers } from "./customers.js";
import { Files } from "./files.js";
import { PaymentLinks } from "./paymentlinks.js";
import { Prices } from "./prices.js";
import { Products } from "./products.js";
import { Transactions } from "./transactions.js";

export class Mpesaflow extends ClientSDK {
  private _businesses?: Businesses;
  get businesses(): Businesses {
    return (this._businesses ??= new Businesses(this._options));
  }

  private _customers?: Customers;
  get customers(): Customers {
    return (this._customers ??= new Customers(this._options));
  }

  private _files?: Files;
  get files(): Files {
    return (this._files ??= new Files(this._options));
  }

  private _paymentLinks?: PaymentLinks;
  get paymentLinks(): PaymentLinks {
    return (this._paymentLinks ??= new PaymentLinks(this._options));
  }

  private _prices?: Prices;
  get prices(): Prices {
    return (this._prices ??= new Prices(this._options));
  }

  private _products?: Products;
  get products(): Products {
    return (this._products ??= new Products(this._options));
  }

  private _transactions?: Transactions;
  get transactions(): Transactions {
    return (this._transactions ??= new Transactions(this._options));
  }
}
