/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { transactionsList } from "../funcs/transactionsList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Transactions extends ClientSDK {
  /**
   * List of all products
   *
   * @remarks
   * List of all products
   */
  async list(
    options?: RequestOptions,
  ): Promise<Array<operations.GetTransactionsResponseBody>> {
    return unwrapAsync(transactionsList(
      this,
      options,
    ));
  }
}
