workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    MpesaFlow API:
        inputs:
            - location: https://api.mpesaflow.com/docs
        overlays:
            - location: .speakeasy\speakeasy-modifications-overlay.yaml
        transformations:
            - filterOperations:
                operations: get_/businesses/{id},patch_/businesses/{id},delete_/businesses/{id},get_/customers/{id},patch_/customers/{id},delete_/customers/{id},get_/files/{id},patch_/files/{id},delete_/files/{id},get_/payment-links/{id},patch_/payment-links/{id},delete_/payment-links/{id},get_/prices/{id},patch_/prices/{id},delete_/prices/{id},get_/products/{id},patch_/products/{id},delete_/products/{id}
                exclude: true
        registry:
            location: registry.speakeasyapi.dev/mpesaflow/sdks/mpesa-flow-api
targets:
    mpesaflow:
        target: typescript
        source: MpesaFlow API
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/mpesaflow/sdks/mpesa-flow-api-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
